### ISSUE TITLE
MRU order messed up

### ISSUE THREAD

**Issue by Droggelbecher** [nixprime/cpsm#15]
The default matcher gives me the most recently used file as first suggestion, then the second most recentely used etc... (given, I didn't type anything yet).
That makes it possible to cycle through most recently used files with ctrl-j/ctrl-k. 
I've gotten pretty used to that behaviour as it allows me to quickly change between the few most recently used files.
Any chance to see cpsm support this as well? (Alternatively: Is there a way to tell CtrlP to use a different matcher for the MRU list?)

**Comment by nixprime** [comment]
I've added a new setting g:cpsm_match_empty_query, which you can set to 0 to prevent cpsm from rearranging items for empty queries; however, this will affect non-MRU mode as well, because CtrlP doesn't inform the matcher whether or not it's in MRU mode. If you want to keep cpsm's behavior for empty queries in non-MRU mode, this can be done with a binding that toggles the value of this setting (see README for an example).

**Comment by Droggelbecher** [comment]
Works nicely for MRU, thanks for the blazingly fast reaction :+1: :)

However for non-MRU mode I now get " ERROR: function takes at most 10 arguments (11 given)" as soon as I type the first character.

**Comment by nixprime** [comment]
Another recent commit changed the Python extension, so you have to rebuild it by redoing step 2 in the installation instructions. Sorry for the inconvenience.

**Comment by Droggelbecher** [comment]
Oh no problem, sorry for not noticing that myself :)
